[package]
name = "rusted-watchword"
version = "0.0.1"
edition = "2021"
authors = ["Thiago Campos"]
license = "GPL-3.0"
repository = "https://github.com/allogarzea/rusted-watchword"
description = "CLI Password Generator created in Rust."
readme = "./README.md"

[dependencies]
rand="0.3.14"